<?php if (!empty($this->_socialProfiles) && $this->isEnabled()) : ?>
<?php $_i = 1 ?>
<!-- CreareSEO Social Schema https://developers.google.com/structured-data/customize/social-profiles -->
 <script type="application/ld+json">
{ "@context" : "http://schema.org",
  "@type" : "Organization",
  "name" : "<?php echo Mage::app()->getStore()->getName(); ?>",
  "url" : "<?php echo Mage::getBaseUrl() ?>",
  "sameAs" : [ <?php foreach ($this->_socialProfiles as $profile) : ?>
  "<?php echo trim($profile) ?>"<?php echo ($_i != $this->socialProfileCount() ? ',' : '') ?><?php $_i++ ?>
  <?php endforeach ?>]
}
</script>
<!-- End CreareSEO Social Schema -->
<?php endif ?>