<!-- Sitelink Search added by CreareSEO -->
<script type="application/ld+json">
{
   "@context": "http://schema.org",
   "@type": "WebSite",
   "url": "<?php echo Mage::getBaseUrl() ?>",
   "potentialAction": {
     "@type": "SearchAction",
     "target": "<?php echo Mage::getBaseUrl() ?>catalogsearch/result/?q={search_term_string}",
     "query-input": "required name=search_term_string"
   }
}
</script>