<?php if (!Mage::helper('core/cookie')->isUserNotAllowSaveCookie()): ?>
    <?php $accountId = Mage::getStoreConfig(Mage_GoogleAnalytics_Helper_Data::XML_PATH_ACCOUNT) ?>
    <!-- Universal Analytics added by CreareSEO -->
    <script type="text/javascript">
        //<![CDATA[
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', '<?php echo $accountId ?>', 'auto');
        <?php if ($this->enableDemographics()): ?>ga('require', 'displayfeatures');
        <?php endif ?>
        ga('send', 'pageview');
        <?php echo $this->_getOrdersTrackingCode() ?>
        <?php echo $this->getAdditionalTrackingCode() ?>

        //]]>
    </script>
<?php endif; ?>