<div class="creareseo-sitemap">
    <div class="sitempan">
        <?php if (Mage::helper('creareseositemap')->showCMS() || Mage::helper('creareseositemap')->showXMLSitemap()): ?>
            <h2><?php echo $this->__('Our Main Site Pages') ?></h2>
            <ul class="siteul <?php echo (Mage::helper('creareseositemap')->fullWidth())? 'full' : '' ?>">
                <?php if (Mage::helper('creareseositemap')->showCMS()): ?>
                    <?php echo $this->getCreareCMSPages(); ?>
                <?php endif; ?>
                <?php if (Mage::helper('creareseositemap')->showXMLSitemap()): ?>
                    <?php
                    $sitemaps = Mage::getModel('sitemap/sitemap')->getCollection();
                    foreach ($sitemaps as $sitemap):
                        $sitemapfilename = $sitemap->getSitemapFilename();
                        if ($sitemapfilename != "" && $sitemap->getStoreId() == Mage::app()->getStore()->getStoreId()):
                            ?>
                            <li><a href="<?php echo Mage::getBaseUrl() . $sitemapfilename; ?>" title="XML Sitemap">XML Sitemap</a></li>
                        <?php endif;
                    endforeach;
                    ?>
            <?php endif; ?>
            </ul>
            <?php endif; ?>
            <?php if (Mage::helper('creareseositemap')->showAccount() || Mage::helper('creareseositemap')->showContact()): ?>
            <ul class="siteul <?php echo (Mage::helper('creareseositemap')->fullWidth())? 'full' : '' ?>">
                <?php if (Mage::helper('creareseositemap')->showContact()): ?>
                    <li><a href="<?php echo Mage::getBaseUrl(); ?>contacts" title="Contact">Contact</a></li>
                <?php endif; ?>
                <?php if (Mage::helper('creareseositemap')->showAccount()): ?>
                    <?php
                    if ($this->helper('customer')->isLoggedIn()) {
                        echo '<li><a href="' . Mage::getBaseUrl() . 'customer/account/index/" title="Account">Account</a></li>';
                        echo '<li><a href="' . Mage::getBaseUrl() . 'customer/account/logout/" title="Log Out">Log Out</a></li>';
                    } else {
                        echo '<li><a href="' . Mage::getBaseUrl() . 'customer/account/" title="Register/Log In">Register/Log In</a></li>';
                    }
                    ?>
                    <li><a href="<?php echo Mage::getBaseUrl(); ?>catalogsearch/advanced" title="Advanced Search">Advanced Search</a></li>
            <?php endif; ?>
            </ul>
    <?php endif; ?>
    </div>
    <?php if (Mage::helper('creareseositemap')->showCategories()): ?>
    <div class="sitempan">
        <h2><?php echo $this->__('Our Categories') ?></h2>
        <?php $_helper = Mage::helper('catalog/category') ?>
            <?php $_categories = $_helper->getStoreCategories() ?>
            <?php if (count($_categories) > 0): ?>
            <ul class="sitecatul <?php echo (Mage::helper('creareseositemap')->fullWidth())? 'full' : '' ?>">
                <?php foreach ($_categories as $_category): ?>
                    <li class="cat">
                        <a href="<?php echo $_helper->getCategoryUrl($_category) ?>" title="<?php echo $_category->getName() ?>"><strong class="strongsm"><?php echo $_category->getName() ?></strong></a>
                            <?php $_category = Mage::getModel('catalog/category')->load($_category->getId()) ?>
                            <?php $_subcategories = $_category->getChildrenCategories() ?>
                            <?php if (count($_subcategories) > 0): ?>
                            <ul>
                                <?php foreach ($_subcategories as $_subcategory): ?>
                <?php $_nextcategory = Mage::getModel('catalog/category')->load($_subcategory->getId()) ?>
                                            <?php $_nextsubcategories = $_nextcategory->getChildrenCategories() ?>
                                    <li>
                                        <a href="<?php echo $_helper->getCategoryUrl($_subcategory) ?>" title="<?php echo $_subcategory->getName() ?>">
                                        <?php echo $_subcategory->getName() ?>
                                        </a>
                                            <?php if (count($_nextsubcategories) > 0): ?>
                                            <ul>
                                                        <?php foreach ($_nextsubcategories as $_nextsubcat): ?>
                                                    <li>
                                                        <a href="<?php echo $_helper->getCategoryUrl($_nextsubcat) ?>" title="<?php echo $_subcategory->getName() ?> - <?php echo $_nextsubcat->getName() ?>">
                                                    <?php echo $_nextsubcat->getName() ?>
                                                        </a>
                                                    </li>
                                            <?php endforeach; ?>
                                            </ul>
                                    <?php endif; ?>
                                    </li>
                            <?php endforeach; ?>
                            </ul>
                    <?php endif; ?>
                    </li>
            <?php endforeach; ?>
            </ul>
        <?php endif; ?>
    </div>
    <?php endif; ?>
</div>