<div class="creareseo-sitemap std">
    <h1><?php echo $this->__("Sitemap") ?></h1>
    <?php echo $this->sitemapHelper()->getConfig('description') ?>
    <h2><?php echo $this->__("Pages") ?></h2>
    <ul>
        <?php if ($_cmsPages = $this->getCmsPages()) : ?>
            <?php foreach ($_cmsPages as $_page) : ?>
                <li><a href="<?php echo $_page->getIdentifier() ?>"><?php echo $_page->getTitle() ?></a></li>
            <?php endforeach ?>
        <?php endif ?>
        <?php foreach ($this->getOtherPages() as $_page) : ?>
            <li><a href="<?php echo $_page['url'] ?>"><?php echo $_page['title'] ?></a></li>
        <?php endforeach ?>
    </ul>
    <?php if ($_categoryTreeHtml = $this->getCategoryTreeHtml()) : ?>
        <h2><?php echo $this->__("Categories") ?></h2>
        <?php echo $_categoryTreeHtml ?>
    <?php endif ?>

    <?php if ($_xmlSitemaps = $this->getXmlSitemaps()) : ?>
        <h2><?php echo $this->__("Sitemaps") ?></h2>
        <ul>
            <?php foreach ($_xmlSitemaps as $_sitemap) : ?>
                <li>
                    <a href="<?php echo $_sitemap->getSitemapFilename() ?>"><?php echo $_sitemap->getSitemapFilename() ?></a>
                </li>
            <?php endforeach ?>
        </ul>
    <?php endif ?>
</div>