<?php
$_helper = $this->helper('catalog/output');
$_product = $this->getProduct();
$_i = 1;
$_totalAverageRating = 0;

?>
<!-- Product Schema added by CreareSEO -->
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "Product",
  "description": "<?php echo $this->cleanString($_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description')) ?>",
  "name": "<?php echo $this->cleanString($_product->getName()) ?>",
  "image": "<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($_product->getImage()) ?>",
  "sku": "<?php echo $this->cleanString($_product->getSku()) ?>",
  "url": "<?php echo $_product->getProductUrl() ?>",
  "offers": {
    <?php if($_product->getTypeId() === 'bundle') : ?>
    <?php $_bundleObject = Mage::getModel('bundle/product_price') ?>
    "@type": "AggregateOffer",
    "lowPrice": "<?php echo $_bundleObject->getTotalPrices($_product,'min',1) ?>",
    "highPrice": "<?php echo $_bundleObject->getTotalPrices($_product,'max',1) ?>",
    <?php else: ?>
    "@type": "Offer",
    "price": "<?php echo number_format(Mage::helper('creareseocore')->getProductStartingprice($_product),2) ?>",
    <?php endif ?>
    "availability": "<?php echo ($_product->isAvailable() ? 'InStock' : 'OutOfStock') ?>",
    "priceCurrency": "<?php echo $this->getCurrency() ?>"
  }<?php if ($this->getReviewsCount()) : ?>,
  "review": [
    <?php foreach ($this->_productReviews as $review) : ?>
    {
      "@type": "Review",
      "author": "<?php echo $review->getNickname() ?>",
      "datePublished": "<?php echo date('Y-d-m', strtotime($review->getCreatedAt())) ?>",
      "description": "<?php echo $this->cleanString($review->getDetail()) ?>",
      "name": "<?php echo $review->getTitle() ?>"<?php $_averageRating = $this->getAverageRating($review->getReviewId()) ?><?php if ($_averageRating >= 1) : ?>,
      "reviewRating": {
        "@type": "Rating",
        "bestRating": "5",
        "ratingValue": "<?php echo $_averageRating ?>",<?php $_totalAverageRating += $_averageRating ?>
        "worstRating": "1"
      }
      <?php endif ?>
    }<?php echo ($_i != $this->getReviewsCount() ? ',' : '') ?>
        <?php $_i++ ?>
    <?php endforeach ?>
  ],
  "aggregateRating": {
    "@type": "AggregateRating",
    <?php $ratingValue = round($_totalAverageRating/$this->getReviewsCount(), 1) ?>
        <?php if ($ratingValue > 0) : ?>
    "ratingValue": "<?php echo $ratingValue ?>",
    <?php else: ?>
    "ratingValue": "1",
    <?php endif ?>
    "reviewCount": "<?php echo $this->getReviewsCount() ?>"
  }
  <?php endif ?>
}
</script>