<?php
$_helper = $this->helper('catalog/output');
$_product = $this->getProduct();
$_i = 1;
?>
<!-- CreareSEO Product Schema https://schema.org/Product -->
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "Product",
  "aggregateRating": {
    "@type": "AggregateRating",
    "ratingValue": "3.5",
    "reviewCount": "<?php echo $this->getReviewsCount() ?>"
  },
  "description": "<?php echo $this->cleanString($_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description')) ?>",
  "name": "<?php echo $this->cleanString($_product->getName()) ?>",
  "image": "<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($_product->getImage()) ?>",
  "sku": "<?php echo $this->cleanString($_product->getSku()) ?>",
  "url": "<?php echo $_product->getProductUrl() ?>",
  "offers": {
    "@type": "Offer",
    "availability": "<?php echo ($_product->isAvailable() ? 'InStock' : 'OutOfStock') ?>",
    "price": "<?php echo number_format($_product->getFinalPrice(),2) ?>",
    "priceCurrency": "<?php echo $this->getCurrency() ?>"
  }<?php if ($this->getReviewsCount()) : ?>,
  <?php endif ?>
  "review": [
    <?php foreach ($this->_productReviews as $review) : ?>
    {
      "@type": "Review",
      "author": "<?php echo $review->getNickname() ?>",
      "datePublished": "<?php echo date('Y-d-m', strtotime($review->getCreatedAt())) ?>",
      "description": "<?php echo $this->cleanString($review->getDetail()) ?>",
      "name": "<?php echo $review->getTitle() ?>"<?php $_averageRating = $this->getAverageRating($review->getReviewId()) ?><?php if ($_averageRating >= 1) : ?>,
      "reviewRating": {
        "@type": "Rating",
        "bestRating": "5",
        "ratingValue": "<?php echo $_averageRating ?>",
        "worstRating": "1"
      }
      <?php endif ?>
    }<?php echo ($_i != $this->getReviewsCount() ? ',' : '') ?>
        <?php $_i++ ?>
    <?php endforeach ?>
  ]
}
</script>
<!-- End CreareSEO Product Schema -->