<fieldset ng-class="creare-info">
    <table>
        <tr>
            <td><img src="//www.creare.co.uk/assets/creareseo.gif" alt="CreareSEO"/></td>
            <td width="10"></td>
            <td>
                <h3>CreareSEO version <?php echo $this->getModuleVersion() ?></h3>
                <p><strong><a href="<?php echo $this->getGitHubPage() ?>" target="_blank">Support</a></strong> - create a GitHub issue
                    <br/><strong><a href="<?php echo $this->getCreareBlogPost() ?>" target="_blank">How To</a></strong>
                    - read our official blog post for our how-to video
                    <br/><strong><a target="_blank" href="<?php echo $this->getGitHubPage() ?>">Collaborate</a></strong>
                    - visit our GitHub repository and send a pull request</p>
            </td>
        </tr>
    </table>
</fieldset>