<fieldset ng-class="creare-info">
	<table>
		<tr>
		<td><img src="//www.creare.co.uk/assets/creareseo.gif" alt="CreareSEO" /></td>
			<td width="10"></td><td>
			<h3>CreareSEO version <?php echo $this->getModuleVersion() ?></h3>
				<p><strong><a href="<?php echo $this->getCreareHelpDesk() ?>" target="_blank">Support</a></strong> - raise a support ticket if you have any issues and we'll try to help
				<br /><strong><a href="<?php echo $this->getCreareWebsite() ?>" target="_blank">SEO</a></strong> - for more about our SEO services, visit our website and get in touch
				<br /><strong><a href="<?php echo $this->getCreareBlogPost() ?>" target="_blank">How To</a></strong> - read our official blog post for our how-to video
				<br /><strong><a target="_blank" href="<?php echo $this->getGitHubPage() ?>">Collaborate</a></strong> - visit our GitHub repository and send a pull request</p>
			</td>
		</tr>
	</table>
</fieldset>